### ISSUE TITLE
Server crash on MC 1.20.1

### ISSUE THREAD

**Issue by winnetrie83** [CodersDownUnder/flowerseeds2#7]
This message appears right before the crash:

```
Suppressed: net.minecraftforge.fml.ModLoadingException: Flower Seeds 2 (flowerseeds) encountered an error during the common_setup event phase
§7java.lang.NullPointerException: Registry Object not present: flowerseeds:dandelion_seed
```
Using MC 1.20.1
Forge 47.2.1
Flowerseeds2-1.20.1-1.1.0

**Comment by Trhod17** [comment]
Can you please provide a full debug log usually found logs/debug.log, using one of these sites

 https://gist.github.com/:      [Free] [SignUp] 100MB
    https://paste.gemwire.uk/:  [Free] 10MB
    https://paste.ee/:                   [Free] 1MB, [SignUp] 6MB
    https://pastebin.com/:          [Free] 512KB, [SignUp] [Paid] 10MB
    https://hastebin.com/:          [Free] 400KB
    https://gist.github.com/:      [Free] [SignUp] 100MB

**Comment by winnetrie83** [comment]
I'm very sorry, but i do not have these files anymore with the crash.
It's already overwritten.
I reported this here, removed the mod and went on with my server.
I can only say, it doesn't happen clientsided. 
As far as i understand it the code wants to access flowerseeds:dandelion_seed, but it hasn't been registered. Could be misspelled or forgotten to register it...

**Comment by winnetrie83** [comment]
So i took some free time to setup a server on my pc and run it with ONLY your mod installed.
Using MC 1.20.1
Forge 47.2.1
Flowerseeds2-1.20.1-1.1.0

and here is the debug.log: https://pastebin.com/32JeRgCW
and here the latest.log: https://pastebin.com/7HwJi4k6

Hopefully it helps.

**Comment by Trhod17** [comment]
should be fixed in latest version https://legacy.curseforge.com/minecraft/mc-mods/flower-seeds/files/4788826

**Comment by Spyro1502** [comment]
[crash-2023-10-30_20.16.05-client.txt](https://github.com/CodersDownUnder/flowerseeds2/files/13209123/crash-2023-10-30_20.16.05-client.txt)
Hi ! I'm still having this crash in 1.1.2
